Check before handling 404 routes
bramus/router pull request #187
Opened 2022-07-28 16:03 UTC by matthew-e-brown

This PR fixes #182.

I have verified that PHPUnit tests still pass. On a side-note, the version of PHP unit in `composer.json` doesn't work with PHP 8 due to the deprecation of `each` that it uses. Might be worth updating it.

2022-07-28 16:45 UTC, bramus requested changes

2022-07-28 16:45 UTC, bramus commented on src/Bramus/Router/Router.php
> +        elseif ($callback && is_callable($callback)) {
By introducing the `elseif`, it also introduces the unwanted side-effect of running the callback when there is no handler and no afterRoute … To not change the existing behavior, the callback should only be run when there was a handler.

2022-07-28 16:45 UTC, bramus commented on src/Bramus/Router/Router.php
> +        elseif ($callback && is_callable($callback)) {
The solution lies at line 291: don’t `&&` the extra condition, but nest it. Then this `elseif` could remain in place.

2022-07-28 16:54 UTC, bramus approved these changes

2022-07-28 17:16 UTC, matthew-e-brown commented
If my investigation is correct, it looks like Git's [recent-ish update to fix CVE-2022-24765](https://github.blog/2022-04-12-git-security-vulnerability-announced/) is making this action fail. Perhaps updating to `v2.4.1` as per actions/checkout#766 would fix it? 🤔

2022-07-28 21:40 UTC, bramus commented
Good find! It took me some attempts, but I have fixed the GitHub Actions build on `master`. If you could merge, then this PR can be tested as well.

2022-07-29 00:17 UTC, matthew-e-brown commented
Just pulled your `master` changes into my fork. Is that what you meant by merge? 😅

2022-07-29 13:56 UTC, merged